// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace PianoTunesAPI.Migrations
{
    [DbContext(typeof(PianoTunesAPIDbContext))]
    [Migration("20240306013550_SecondCreate")]
    partial class SecondCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GenreSong", b =>
                {
                    b.Property<int>("GenresId")
                        .HasColumnType("integer");

                    b.Property<int>("SongsId")
                        .HasColumnType("integer");

                    b.HasKey("GenresId", "SongsId");

                    b.HasIndex("SongsId");

                    b.ToTable("GenreSong");
                });

            modelBuilder.Entity("PianoTunesAPI.Models.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 31,
                            Bio = "Young, handsome man who loves to write a good love song.",
                            Name = "Joey Ebach"
                        },
                        new
                        {
                            Id = 2,
                            Age = 52,
                            Bio = "Wrote many classic love songs, which have been played at many weddings.",
                            Name = "Edwin McCain"
                        },
                        new
                        {
                            Id = 3,
                            Age = 53,
                            Bio = "Christian artist who writes inspiring music about God.",
                            Name = "Chris Tomlin"
                        },
                        new
                        {
                            Id = 4,
                            Age = 52,
                            Bio = "She has a beautiful voice and loves singing upbeat tunes.",
                            Name = "Whitney Houston"
                        },
                        new
                        {
                            Id = 5,
                            Age = 55,
                            Bio = "She can hold her pitch like no one else!",
                            Name = "Mariah Carey"
                        });
                });

            modelBuilder.Entity("PianoTunesAPI.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Soul"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Pop"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Rock"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Country"
                        });
                });

            modelBuilder.Entity("PianoTunesAPI.Models.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Album")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ArtistId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Length")
                        .HasColumnType("numeric");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Album = "Forever",
                            ArtistId = 5,
                            Length = 3.01m,
                            Title = "Looking Good"
                        },
                        new
                        {
                            Id = 2,
                            Album = "Games",
                            ArtistId = 2,
                            Length = 3.11m,
                            Title = "Could Not Ask For More"
                        },
                        new
                        {
                            Id = 3,
                            Album = "Hero",
                            ArtistId = 1,
                            Length = 4.01m,
                            Title = "In Your Eyes"
                        },
                        new
                        {
                            Id = 4,
                            Album = "Games",
                            ArtistId = 2,
                            Length = 5.01m,
                            Title = "I'll Be"
                        },
                        new
                        {
                            Id = 5,
                            Album = "SoulMates",
                            ArtistId = 4,
                            Length = 3.31m,
                            Title = "I Will Always Love You"
                        });
                });

            modelBuilder.Entity("GenreSong", b =>
                {
                    b.HasOne("PianoTunesAPI.Models.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PianoTunesAPI.Models.Song", null)
                        .WithMany()
                        .HasForeignKey("SongsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PianoTunesAPI.Models.Song", b =>
                {
                    b.HasOne("PianoTunesAPI.Models.Artist", "Artist")
                        .WithMany("Songs")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("PianoTunesAPI.Models.Artist", b =>
                {
                    b.Navigation("Songs");
                });
#pragma warning restore 612, 618
        }
    }
}
